name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
          
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
      
      - name: Install wasm-pack and wasm-opt
        run: |
          # Install wasm-pack
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          
          # Install binaryen (includes wasm-opt)
          npm install -g wasm-opt
          
      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            wasm/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install dependencies
        run: yarn install --immutable
      
      - name: Build WASM module
        run: |
          cd wasm
          # Build without wasm-opt first
          wasm-pack build --target web --out-dir pkg --release --no-opt
          
          # Run wasm-opt manually with correct flags
          if command -v wasm-opt &> /dev/null; then
            echo "Running wasm-opt with bulk-memory and nontrapping-float-to-int..."
            wasm-opt pkg/gene_sim_core_bg.wasm \
              -O3 \
              --enable-bulk-memory \
              --enable-nontrapping-float-to-int \
              -o pkg/gene_sim_core_bg_opt.wasm
            if [ $? -eq 0 ]; then
              mv pkg/gene_sim_core_bg_opt.wasm pkg/gene_sim_core_bg.wasm
              echo "wasm-opt successful!"
            else
              echo "wasm-opt failed, using unoptimized version"
            fi
          fi
          
          cd ..
          # Copy WASM files to src directory for bundling
          mkdir -p src/wasm
          cp wasm/pkg/gene_sim_core_bg.wasm src/wasm/ || true
          cp wasm/pkg/gene_sim_core.js src/wasm/ || true
          cp wasm/pkg/gene_sim_core.d.ts src/wasm/ || true

      - name: Build
        run: yarn build
        env:
          NODE_ENV: production

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4